---
build: off
deploy: off

image:
  - Ubuntu
  # - Visual Studio 2015

install:
  - sh: |
      [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" &&
      rvm use "ruby-head"


test_script:
  - ruby --version
  - ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"
  - ruby -ropenssl -e "puts OpenSSL::OPENSSL_LIBRARY_VERSION"
