---
build: off
deploy: off

image:
  - Ubuntu
  # - Visual Studio 2015

install:
#  - sh: rvm install "ruby-2.6.0dev"
  - sh: rvm use "ruby-head"
  

test_script:
  - ruby --version
  - ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"
  - ruby -ropenssl -e "puts OpenSSL::OPENSSL_LIBRARY_VERSION"
